/*
 * NGINX Plus REST API
 *
 * NGINX Plus REST [API](https://nginx.org/en/docs/http/ngx_http_api_module.html) provides access to NGINX Plus status information, on-the-fly configuration of upstream servers and key-value pairs management for [http](https://nginx.org/en/docs/http/ngx_http_keyval_module.html) and [stream](https://nginx.org/en/docs/stream/ngx_stream_keyval_module.html).
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type NginxHttpUpstreamPeer struct {

	// The ID of the server.
	Id int32 `json:"id,omitempty"`

	// An  <a href=\"https://nginx.org/en/docs/http/ngx_http_upstream_module.html#server\">address</a> of the server.
	Server string `json:"server,omitempty"`

	// The <a href=\"https://nginx.org/en/docs/http/ngx_http_upstream_module.html#service\">service</a> parameter value of the <a href=\"https://nginx.org/en/docs/http/ngx_http_upstream_module.html#server\">server</a> directive.
	Service string `json:"service,omitempty"`

	// The name of the server specified in the <a href=\"https://nginx.org/en/docs/http/ngx_http_upstream_module.html#server\">server</a> directive.
	Name string `json:"name,omitempty"`

	// A boolean value indicating whether the server is a <a href=\"https://nginx.org/en/docs/http/ngx_http_upstream_module.html#backup\">backup</a> server.
	Backup bool `json:"backup,omitempty"`

	// <a href=\"https://nginx.org/en/docs/http/ngx_http_upstream_module.html#weight\">Weight</a> of the server.
	Weight int32 `json:"weight,omitempty"`

	// Current state, which may be one of “<code>up</code>”, “<code>draining</code>”, “<code>down</code>”, “<code>unavail</code>”, “<code>checking</code>”, and “<code>unhealthy</code>”.
	State string `json:"state,omitempty"`

	// The current number of active connections.
	Active int32 `json:"active,omitempty"`

	// The <a href=\"https://nginx.org/en/docs/http/ngx_http_upstream_module.html#max_conns\">max_conns</a> limit for the server.
	MaxConns int32 `json:"max_conns,omitempty"`

	// The total number of client requests forwarded to this server.
	Requests int32 `json:"requests,omitempty"`

	Responses *NginxHttpUpstreamPeerResponses `json:"responses,omitempty"`

	// The total number of bytes sent to this server.
	Sent int32 `json:"sent,omitempty"`

	// The total number of bytes received from this server.
	Received int32 `json:"received,omitempty"`

	// The total number of unsuccessful attempts to communicate with the server.
	Fails int32 `json:"fails,omitempty"`

	// How many times the server became unavailable for client requests (state “<code>unavail</code>”) due to the number of unsuccessful attempts reaching the <a href=\"https://nginx.org/en/docs/http/ngx_http_upstream_module.html#max_fails\">max_fails</a> threshold.
	Unavail int32 `json:"unavail,omitempty"`

	HealthChecks *NginxHttpUpstreamPeerHealthChecks `json:"health_checks,omitempty"`

	// Total time the server was in the “<code>unavail</code>”, “<code>checking</code>”, and “<code>unhealthy</code>” states.
	Downtime int32 `json:"downtime,omitempty"`

	// The time (in milliseconds since Epoch) when the server became “<code>unavail</code>”, “<code>checking</code>”, or “<code>unhealthy</code>”.
	Downstart time.Time `json:"downstart,omitempty"`

	// The time (in milliseconds since Epoch) when the server was last selected to process a request.
	Selected time.Time `json:"selected,omitempty"`

	// The average time to get the <a href=\"https://nginx.org/en/docs/http/ngx_http_upstream_module.html#var_upstream_header_time\">response header</a> from the server.
	HeaderTime int32 `json:"header_time,omitempty"`

	// The average time to get the <a href=\"https://nginx.org/en/docs/http/ngx_http_upstream_module.html#var_upstream_response_time\">full response</a> from the server.
	ResponseTime int32 `json:"response_time,omitempty"`
}
