/*
 * NGINX Plus REST API
 *
 * NGINX Plus REST [API](https://nginx.org/en/docs/http/ngx_http_api_module.html) provides access to NGINX Plus status information, on-the-fly configuration of upstream servers and key-value pairs management for [http](https://nginx.org/en/docs/http/ngx_http_keyval_module.html) and [stream](https://nginx.org/en/docs/stream/ngx_stream_keyval_module.html).
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NginxSlabZoneSlot struct {

	// The current number of used memory slots.
	Used int32 `json:"used,omitempty"`

	// The current number of free memory slots.
	Free int32 `json:"free,omitempty"`

	// The total number of attempts to allocate memory of specified size.
	Reqs int32 `json:"reqs,omitempty"`

	// The number of unsuccessful attempts to allocate memory of specified size.
	Fails int32 `json:"fails,omitempty"`
}
