/*
 * NGINX Plus REST API
 *
 * NGINX Plus REST [API](https://nginx.org/en/docs/http/ngx_http_api_module.html) provides access to NGINX Plus status information, on-the-fly configuration of upstream servers and key-value pairs management for [http](https://nginx.org/en/docs/http/ngx_http_keyval_module.html) and [stream](https://nginx.org/en/docs/stream/ngx_stream_keyval_module.html).
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NginxHttpCacheUpdating struct {

	// The total number of expired responses read from the cache while responses were being updated (see <a href=\"https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_use_stale_updating\">proxy_cache_use_stale</a> and other “<code>*_cache_use_stale</code>” directives).
	Responses int32 `json:"responses,omitempty"`

	// The total number of bytes read from the cache.
	Bytes int32 `json:"bytes,omitempty"`
}
