/*
 * NGINX Plus REST API
 *
 * NGINX Plus REST [API](https://nginx.org/en/docs/http/ngx_http_api_module.html) provides access to NGINX Plus status information, on-the-fly configuration of upstream servers and key-value pairs management for [http](https://nginx.org/en/docs/http/ngx_http_keyval_module.html) and [stream](https://nginx.org/en/docs/stream/ngx_stream_keyval_module.html).
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The number of accepted, dropped, active, and idle connections. 
type NginxConnections struct {

	// The total number of accepted client connections.
	Accepted int32 `json:"accepted,omitempty"`

	// The total number of dropped client connections.
	Dropped int32 `json:"dropped,omitempty"`

	// The current number of active client connections.
	Active int32 `json:"active,omitempty"`

	// The current number of idle client connections.
	Idle int32 `json:"idle,omitempty"`
}
