/*
 * NGINX Plus REST API
 *
 * NGINX Plus REST [API](https://nginx.org/en/docs/http/ngx_http_api_module.html) provides access to NGINX Plus status information, on-the-fly configuration of upstream servers and key-value pairs management for [http](https://nginx.org/en/docs/http/ngx_http_keyval_module.html) and [stream](https://nginx.org/en/docs/stream/ngx_stream_keyval_module.html).
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NginxHttpUpstream struct {

	Peers *NginxHttpUpstreamPeerMap `json:"peers,omitempty"`

	// The current number of idle <a href=\"https://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive\">keepalive</a> connections.
	Keepalive int32 `json:"keepalive,omitempty"`

	// The current number of servers removed from the group but still processing active client requests.
	Zombies int32 `json:"zombies,omitempty"`

	// The name of the shared memory <a href=\"https://nginx.org/en/docs/http/ngx_http_upstream_module.html#zone\">zone</a> that keeps the group’s configuration and run-time state.
	Zone string `json:"zone,omitempty"`

	Queue *NginxHttpUpstreamQueue `json:"queue,omitempty"`
}
