/*
 * NGINX Plus REST API
 *
 * NGINX Plus REST [API](https://nginx.org/en/docs/http/ngx_http_api_module.html) provides access to NGINX Plus status information, on-the-fly configuration of upstream servers and key-value pairs management for [http](https://nginx.org/en/docs/http/ngx_http_keyval_module.html) and [stream](https://nginx.org/en/docs/stream/ngx_stream_keyval_module.html).
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NginxHttpCacheBypass struct {

	// The total number of responses not looked up in the cache due to the <a href=\"https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_bypass\">proxy_cache_bypass</a> and other “<code>*_cache_bypass</code>” directives.
	Responses int32 `json:"responses,omitempty"`

	// The total number of bytes read from the proxied server.
	Bytes int32 `json:"bytes,omitempty"`

	// The total number of responses written to the cache.
	ResponsesWritten int32 `json:"responses_written,omitempty"`

	// The total number of bytes written to the cache.
	BytesWritten int32 `json:"bytes_written,omitempty"`
}
