/*
 * NGINX Plus REST API
 *
 * NGINX Plus REST [API](https://nginx.org/en/docs/http/ngx_http_api_module.html) provides access to NGINX Plus status information, on-the-fly configuration of upstream servers and key-value pairs management for [http](https://nginx.org/en/docs/http/ngx_http_keyval_module.html) and [stream](https://nginx.org/en/docs/stream/ngx_stream_keyval_module.html).
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Dynamically configurable parameters of an HTTP upstream <a href=\"https://nginx.org/en/docs/http/ngx_http_upstream_module.html#server\">server</a>: 
type NginxHttpUpstreamConfServer struct {

	// The ID of the HTTP upstream server. The ID is assigned automatically and cannot be changed.
	Id int32 `json:"id,omitempty"`

	// Same as the <a href=\"https://nginx.org/en/docs/http/ngx_http_upstream_module.html#address\">address</a> parameter of the HTTP upstream server. When adding a server, it is possible to specify it as a domain name. In this case, changes of the IP addresses that correspond to a domain name will be monitored and automatically applied to the upstream configuration without the need of restarting nginx. This requires the <a href=\"https://nginx.org/en/docs/http/ngx_http_core_module.html#resolver\">resolver</a> directive in the “<code>http</code>” block. See also the <a href=\"https://nginx.org/en/docs/http/ngx_http_upstream_module.html#resolve\">resolve</a> parameter of the HTTP upstream server.
	Server string `json:"server,omitempty"`

	// Same as the <a href=\"https://nginx.org/en/docs/http/ngx_http_upstream_module.html#service\">service</a> parameter of the HTTP upstream server. This parameter cannot be changed.
	Service string `json:"service,omitempty"`

	// Same as the <a href=\"https://nginx.org/en/docs/http/ngx_http_upstream_module.html#weight\">weight</a> parameter of the HTTP upstream server.
	Weight int32 `json:"weight,omitempty"`

	// Same as the <a href=\"https://nginx.org/en/docs/http/ngx_http_upstream_module.html#max_conns\">max_conns</a> parameter of the HTTP upstream server.
	MaxConns int32 `json:"max_conns,omitempty"`

	// Same as the <a href=\"https://nginx.org/en/docs/http/ngx_http_upstream_module.html#max_fails\">max_fails</a> parameter of the HTTP upstream server.
	MaxFails int32 `json:"max_fails,omitempty"`

	// Same as the <a href=\"https://nginx.org/en/docs/http/ngx_http_upstream_module.html#fail_timeout\">fail_timeout</a> parameter of the HTTP upstream server.
	FailTimeout string `json:"fail_timeout,omitempty"`

	// Same as the <a href=\"https://nginx.org/en/docs/http/ngx_http_upstream_module.html#slow_start\">slow_start</a> parameter of the HTTP upstream server.
	SlowStart string `json:"slow_start,omitempty"`

	// Same as the <a href=\"https://nginx.org/en/docs/http/ngx_http_upstream_module.html#route\">route</a> parameter of the HTTP upstream server.
	Route string `json:"route,omitempty"`

	// When <code>true</code>, adds a <a href=\"https://nginx.org/en/docs/http/ngx_http_upstream_module.html#backup\">backup</a> server. This parameter cannot be changed.
	Backup bool `json:"backup,omitempty"`

	// Same as the <a href=\"https://nginx.org/en/docs/http/ngx_http_upstream_module.html#down\">down</a> parameter of the HTTP upstream server.
	Down bool `json:"down,omitempty"`

	// Same as the <a href=\"https://nginx.org/en/docs/http/ngx_http_upstream_module.html#drain\">drain</a> parameter of the HTTP upstream server.
	Drain bool `json:"drain,omitempty"`

	// Parent server ID of the resolved server. The ID is assigned automatically and cannot be changed.
	Parent string `json:"parent,omitempty"`

	// Hostname of the resolved server. The hostname is assigned automatically and cannot be changed.
	Host string `json:"host,omitempty"`
}
