/*
 * NGINX Plus REST API
 *
 * NGINX Plus REST [API](https://nginx.org/en/docs/http/ngx_http_api_module.html) provides access to NGINX Plus status information, on-the-fly configuration of upstream servers and key-value pairs management for [http](https://nginx.org/en/docs/http/ngx_http_keyval_module.html) and [stream](https://nginx.org/en/docs/stream/ngx_stream_keyval_module.html).
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Synchronization information per node in a cluster.
type NginxStreamZoneSyncStatus struct {

	// The number of bytes received by this node.
	BytesIn int32 `json:"bytes_in,omitempty"`

	// The number of messages received by this node.
	MsgsIn int32 `json:"msgs_in,omitempty"`

	// The number of messages sent by this node.
	MsgsOut int32 `json:"msgs_out,omitempty"`

	// The number of bytes sent by this node.
	BytesOut int32 `json:"bytes_out,omitempty"`

	// The number of peers this node is connected to.
	NodesOnline int32 `json:"nodes_online,omitempty"`
}
