/*
 * NGINX Plus REST API
 *
 * NGINX Plus REST [API](https://nginx.org/en/docs/http/ngx_http_api_module.html) provides access to NGINX Plus status information, on-the-fly configuration of upstream servers and key-value pairs management for [http](https://nginx.org/en/docs/http/ngx_http_keyval_module.html) and [stream](https://nginx.org/en/docs/stream/ngx_stream_keyval_module.html).
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NginxStreamServerZone struct {

	// The number of client connections that are currently being processed.
	Processing int32 `json:"processing,omitempty"`

	// The total number of connections accepted from clients.
	Connections int32 `json:"connections,omitempty"`

	Sessions *NginxStreamServerZoneSessions `json:"sessions,omitempty"`

	// The total number of connections completed without creating a session.
	Discarded int32 `json:"discarded,omitempty"`

	// The total number of bytes received from clients.
	Received int32 `json:"received,omitempty"`

	// The total number of bytes sent to clients.
	Sent int32 `json:"sent,omitempty"`
}
