/*
 * NGINX Plus REST API
 *
 * NGINX Plus REST [API](https://nginx.org/en/docs/http/ngx_http_api_module.html) provides access to NGINX Plus status information, on-the-fly configuration of upstream servers and key-value pairs management for [http](https://nginx.org/en/docs/http/ngx_http_keyval_module.html) and [stream](https://nginx.org/en/docs/stream/ngx_stream_keyval_module.html).
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NginxSslObject struct {

	// The total number of successful SSL handshakes.
	Handshakes int32 `json:"handshakes,omitempty"`

	// The total number of failed SSL handshakes.
	HandshakesFailed int32 `json:"handshakes_failed,omitempty"`

	// The total number of session reuses during SSL handshake.
	SessionReuses int32 `json:"session_reuses,omitempty"`
}
