/*
 * NGINX Plus REST API
 *
 * NGINX Plus REST [API](https://nginx.org/en/docs/http/ngx_http_api_module.html) provides access to NGINX Plus status information, on-the-fly configuration of upstream servers and key-value pairs management for [http](https://nginx.org/en/docs/http/ngx_http_keyval_module.html) and [stream](https://nginx.org/en/docs/stream/ngx_stream_keyval_module.html).
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NginxHttpCache struct {

	// The current size of the cache.
	Size int32 `json:"size,omitempty"`

	// The limit on the maximum size of the cache specified in the configuration.
	MaxSize int32 `json:"max_size,omitempty"`

	// A boolean value indicating whether the “cache loader” process is still loading data from disk into the cache.
	Cold bool `json:"cold,omitempty"`

	Hit *NginxHttpCacheHit `json:"hit,omitempty"`

	Stale *NginxHttpCacheStale `json:"stale,omitempty"`

	Updating *NginxHttpCacheUpdating `json:"updating,omitempty"`

	Revalidated *NginxHttpCacheRevalidated `json:"revalidated,omitempty"`

	Miss *NginxHttpCacheMiss `json:"miss,omitempty"`

	Expired *NginxHttpCacheExpired `json:"expired,omitempty"`

	Bypass *NginxHttpCacheBypass `json:"bypass,omitempty"`
}
