/*
 * NGINX Plus REST API
 *
 * NGINX Plus REST [API](https://nginx.org/en/docs/http/ngx_http_api_module.html) provides access to NGINX Plus status information, on-the-fly configuration of upstream servers and key-value pairs management for [http](https://nginx.org/en/docs/http/ngx_http_keyval_module.html) and [stream](https://nginx.org/en/docs/stream/ngx_stream_keyval_module.html).
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// For the requests <a href=\"https://nginx.org/en/docs/http/ngx_http_upstream_module.html#queue\">queue</a>, the following data are provided: 
type NginxHttpUpstreamQueue struct {

	// The current number of requests in the queue.
	Size int32 `json:"size,omitempty"`

	// The maximum number of requests that can be in the queue at the same time.
	MaxSize int32 `json:"max_size,omitempty"`

	// The total number of requests rejected due to the queue overflow.
	Overflows int32 `json:"overflows,omitempty"`
}
