/*
 * NGINX Plus REST API
 *
 * NGINX Plus REST [API](https://nginx.org/en/docs/http/ngx_http_api_module.html) provides access to NGINX Plus status information, on-the-fly configuration of upstream servers and key-value pairs management for [http](https://nginx.org/en/docs/http/ngx_http_keyval_module.html) and [stream](https://nginx.org/en/docs/stream/ngx_stream_keyval_module.html).
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The total number of completed sessions, and the number of sessions completed with status codes “<code>2xx</code>”, “<code>4xx</code>”, or “<code>5xx</code>”.
type NginxStreamServerZoneSessions struct {

	// The total number of sessions completed with <a href=\"https://nginx.org/en/docs/stream/ngx_stream_core_module.html#var_status\">status codes</a> “<code>2xx</code>”.
	Var2xx int32 `json:"2xx,omitempty"`

	// The total number of sessions completed with <a href=\"https://nginx.org/en/docs/stream/ngx_stream_core_module.html#var_status\">status codes</a> “<code>4xx</code>”.
	Var4xx int32 `json:"4xx,omitempty"`

	// The total number of sessions completed with <a href=\"https://nginx.org/en/docs/stream/ngx_stream_core_module.html#var_status\">status codes</a> “<code>5xx</code>”.
	Var5xx int32 `json:"5xx,omitempty"`

	// The total number of completed client sessions.
	Total int32 `json:"total,omitempty"`
}
