/*
 * NGINX Plus REST API
 *
 * NGINX Plus REST [API](https://nginx.org/en/docs/http/ngx_http_api_module.html) provides access to NGINX Plus status information, on-the-fly configuration of upstream servers and key-value pairs management for [http](https://nginx.org/en/docs/http/ngx_http_keyval_module.html) and [stream](https://nginx.org/en/docs/stream/ngx_stream_keyval_module.html).
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// General information about nginx: 
type NginxObject struct {

	// Version of nginx.
	Version string `json:"version,omitempty"`

	// Name of nginx build.
	Build string `json:"build,omitempty"`

	// The address of the server that accepted status request.
	Address string `json:"address,omitempty"`

	// The total number of configuration <a href=\"https://nginx.org/en/docs/control.html#reconfiguration\">reloads</a>.
	Generation int32 `json:"generation,omitempty"`

	// Time of the last reload of configuration, in milliseconds since Epoch.
	LoadTimestamp time.Time `json:"load_timestamp,omitempty"`

	// Current time in milliseconds since Epoch.
	Timestamp time.Time `json:"timestamp,omitempty"`

	// The ID of the worker process that handled status request.
	Pid int32 `json:"pid,omitempty"`

	// The ID of the master process that started the <a href=\"https://nginx.org/en/docs/http/ngx_http_status_module.html#pid\">worker process</a>.
	Ppid int32 `json:"ppid,omitempty"`
}
